export const FILTER_SELECT_TYPE = {
  type: {
    name: "type",
    labelName: "Type",
    menuList: [
      "grass",
      "poison",
      "fire",
      "flying",
      "water",
      "bug",
      "normal",
      "electric",
      "ground",
      "fairy",
      "fighting",
      "psychic",
      "rock",
      "steel",
      "ice",
      "ghost",
      "dragon",
    ],
  },
  ability: {
    name: "ability",
    labelName: "Ability",
    menuList: [
      "overgrow",
      "chlorophyll",
      "blaze",
      "solar-power",
      "torrent",
      "rain-dish",
      "shield-dust",
      "run-away",
      "shed-skin",
      "compound-eyes",
      "tinted-lens",
      "swarm",
      "sniper",
      "keen-eye",
      "tangled-feet",
      "big-pecks",
    ],
  },
};
